- name: configure frontend server
  hosts: fronend
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx  
      state: started
      enabled: yes 